<a href="https://colab.research.google.com/github/xeeteex/MLtrainingachs/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Introduction to Numpy

what will we cover?

*   creating arrays
*   multi dimensional array
*   randomly generted arrays
*   element wise operators
  - comparison operations
  - logiacal operations

* summarizing operations  



## Single Dimensional arrays


In [ ]:
import numpy as np

Creating arrays

In [ ]:
var= np.zeros(5)
print(type(var))

<class 'numpy.ndarray'>


In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.full(10, 1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [ ]:
v= np.array([1, 2, 3, 4])
v[2]=5
v


array([1, 2, 5, 4])

In [ ]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

Create arrays with evenly spaced numbers within specfied range

In [ ]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multidimensiona Arrays

In [ ]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
# Create an MD unit Array of Size (5,2)
# Generate a random array of size (3,5) with elements of your choice
# Update the element of an array with index

In [ ]:
v=np.array([[1, 2, 3, 4, 5],[2, 3, 4, 5, 6],[3, 4, 5, 6, 7]])
v

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [ ]:
v= np.array([[1, 2, 3, 4, 5],[2, 3, 4, 5, 6],[3, 4, 5, 6, 7]])
v[1, 4] = 1
v



array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 1],
       [3, 4, 5, 6, 7]])

In [ ]:
v[2] = [1, 1, 1, 1, 1]
v



array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
v[:, 2] = [2, 2, 2]
v

array([[1, 2, 2, 4, 5],
       [2, 3, 2, 5, 1],
       [1, 1, 2, 1, 1]])

#Randomly Generated arrays



- NumPy can create arrays filled with random numbers.

- To ensure the reproducibility, you can set a seed using np.random.seed()

- Everytime you run the code with np.random.seed(2), it will generate the exact same random numbers.

If you remove or change the seed values, the sequence of random numbers will be changed




In [ ]:
np.random.rand(3)

array([0.57427776, 0.28233137, 0.66040962])

In [ ]:
np.random.seed(3)
np.random.rand(3)

array([0.5507979 , 0.70814782, 0.29090474])

In [ ]:
np.random.rand(5,3)

array([[0.51082761, 0.89294695, 0.89629309],
       [0.12558531, 0.20724288, 0.0514672 ],
       [0.44080984, 0.02987621, 0.45683322],
       [0.64914405, 0.27848728, 0.6762549 ],
       [0.59086282, 0.02398188, 0.55885409]])

In [ ]:
np.random.seed(5)
np.random.rand(5,3)


array([[0.22199317, 0.87073231, 0.20671916],
       [0.91861091, 0.48841119, 0.61174386],
       [0.76590786, 0.51841799, 0.2968005 ],
       [0.18772123, 0.08074127, 0.7384403 ],
       [0.44130922, 0.15830987, 0.87993703]])

In [ ]:
np.random.randn(5,2)

array([[-0.2556969 ,  0.35296199],
       [ 0.75412055,  0.61217823],
       [ 0.61185614, -0.7016439 ],
       [ 1.39647672, -0.60757943],
       [-0.37279728,  1.06034711]])

In [ ]:
np.random.seed(223)
np.random.randint(low=0, high=100, size=(5,2))

array([[94, 17],
       [62, 47],
       [66, 30],
       [39, 26],
       [76, 44]])

In [ ]:
#Comparison Operations
#You canperform element wise comparisions and create boolean arrays


In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
b=([10, 12, 14, 16, 18])
b

[10, 12, 14, 16, 18]

In [ ]:
a>=2

array([False, False,  True,  True,  True])

In [ ]:
a>b

array([False, False, False, False, False])

In [ ]:
# Summarizing
# NumPy provides functions for summarizing  array of data
a

array([0, 1, 2, 3, 4])

In [ ]:
#standard deviation
a.std()

1.4142135623730951

In [ ]:
#min value of an array
a.min()

0

In [ ]:
#max value of an array
a.max()

4

In [ ]:
#sum of elements of an array
a.sum()

10