<a href="https://colab.research.google.com/github/xeeteex/MLtrainingachs/blob/main/tensorflow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



# Introduction to Tensor


In [1]:
import tensorflow as tf
print(tf.__version__)

2.18.0


## Creating tensor flow with tf.constants()

In [2]:
scalar = tf.constant(6)

In [3]:
print (scalar)

tf.Tensor(6, shape=(), dtype=int32)


In [4]:
print("scalar dimensions:",scalar.ndim)

scalar dimensions: 0


In [5]:
vector = tf.constant([10,10])

In [6]:
print(vector)

tf.Tensor([10 10], shape=(2,), dtype=int32)


In [7]:
print("vector distance:",vector.ndim)

vector distance: 1


In [8]:
matrix = tf.constant([[10,7],[7,10]])
print (matrix)
print("matrix distance:",matrix.ndim)

tf.Tensor(
[[10  7]
 [ 7 10]], shape=(2, 2), dtype=int32)
matrix distance: 2


In [9]:
tensor= (tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]))
print(tensor)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


In [11]:
print("tensor dimension:",tensor.ndim)

tensor dimension: 3


what we created so far
 - scalar :a single number
 - vector : anumber with direction(eg.windspeed and direction)
 - matrix :

## Creating Tensor with tf.variables

In [12]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [17]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

we cant update constant tensors, only variable tensors can be updated

## Creating Random Tensors

In [18]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_1


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [21]:
random_2 = tf.random.Generator.from_seed(4)
random_2 = random_2.normal(shape=(3,2))
random_2


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 1.0019137 ,  0.6735137 ],
       [ 0.06987712, -1.4077919 ],
       [ 1.0278524 ,  0.27974114]], dtype=float32)>

In [22]:
random_1,random_2,random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 1.0019137 ,  0.6735137 ],
        [ 0.06987712, -1.4077919 ],
        [ 1.0278524 ,  0.27974114]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

## Shuffle the orders of elements in Tensor

### Turn numpy arrays into tensor

In [24]:
import numpy as np
numpy_A  = np.arange(1,25,dtype = np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [25]:
A= tf.constant(numpy_A,shape=(2,3,4))
B = tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)